--
-- PostgreSQL database dump
--

-- Dumped from database version 13.18
-- Dumped by pg_dump version 14.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: generative-art_game_image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."generative-art_game_image" (
    id integer NOT NULL,
    image_path character varying(512) NOT NULL,
    original_prompt text NOT NULL,
    difficulty integer DEFAULT 1 NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    target_words json NOT NULL
);


ALTER TABLE public."generative-art_game_image" OWNER TO postgres;

--
-- Name: generative-art_game_image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."generative-art_game_image" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."generative-art_game_image_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: generative-art_game_image; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."generative-art_game_image" (id, image_path, original_prompt, difficulty, active, created_at, target_words) FROM stdin;
295	/game-images/puns/time_flies.png	A surreal image of a clock with butterfly wings flying through a blue sky	2	t	2025-03-05 17:35:11.68753-05	["time","flies"]
296	/game-images/puns/bread_winner.png	A loaf of bread wearing a gold medal and standing on a winner's podium	2	t	2025-03-05 17:35:11.689476-05	["bread","winner"]
297	/game-images/puns/brain_freeze.png	A cartoon brain character trapped in an ice cube, looking cold	2	t	2025-03-05 17:35:11.690016-05	["brain","freeze"]
298	/game-images/puns/hot_dog.png	A dachshund dog wearing sunglasses and lying on a beach towel under the sun	1	t	2025-03-05 17:35:11.690564-05	["hot","dog"]
299	/game-images/puns/cat_nap.png	A cute cat sleeping peacefully on a giant napkin	1	t	2025-03-05 17:35:11.691225-05	["cat","nap"]
300	/game-images/puns/bookworm.png	A cartoon worm wearing glasses and reading a book in a library	2	t	2025-03-05 17:35:11.692191-05	["book","worm"]
301	/game-images/puns/eye_candy.png	A realistic eyeball made of colorful candy and lollipops	3	t	2025-03-05 17:35:11.692951-05	["eye","candy"]
302	/game-images/puns/couch_potato.png	A potato character with arms and legs lounging on a couch watching TV	2	t	2025-03-05 17:35:11.697318-05	["couch","potato"]
303	/game-images/puns/fish_out_of_water.png	A fish with a confused expression flopping in a desert with cacti	3	t	2025-03-05 17:35:11.699128-05	["fish","water"]
304	/game-images/puns/spill_the_beans.png	Coffee beans spilling out of an overturned coffee cup on a table	3	t	2025-03-05 17:35:11.699705-05	["spill","beans"]
305	/game-images/puns/monkey_business.png	Monkeys in business suits having a meeting in an office	3	t	2025-03-05 17:35:11.700317-05	["monkey","business"]
306	/game-images/puns/pig_out.png	A pig sitting at a table with an empty plate and many food wrappers	2	t	2025-03-05 17:35:11.700931-05	["pig","out"]
307	/game-images/puns/chicken_scratch.png	A chicken using its feet to draw or write on the ground	4	t	2025-03-05 17:35:11.701697-05	["chicken","scratch"]
308	/game-images/puns/holy_cow.png	A cow with a halo floating above its head in a heavenly setting	2	t	2025-03-05 17:35:11.703071-05	["holy","cow"]
309	/game-images/puns/elephant_in_the_room.png	A living room with people ignoring a large elephant standing among them	2	t	2025-03-05 17:35:11.703932-05	["elephant","room"]
310	/game-images/puns/velvet_pumpkin.png	Visualize a pumpkin with a lush, velvet surface. Its deep orange hue should contrast beautifully against a clean white background.	1	t	2025-03-05 17:35:37.437312-05	["velvet","pumpkin"]
311	/game-images/puns/glassy_penguin.png	Imagine a penguin made completely out of glass, catching the cold sunlight as it slides on an iceberg.	2	t	2025-03-05 17:35:37.439792-05	["glassy","penguin"]
312	/game-images/puns/giant_teacup.png	Picture a teacup, large enough for a person to sit in comfortably, filled with steaming hot tea and situated in a quiet, peaceful garden.	3	t	2025-03-05 17:35:37.441369-05	["giant","teacup"]
313	/game-images/puns/holographic_castle.png	Envision a castle shimmering in a spectrum of colors, built entirely from holograms. The castle should still feature typical architecture, but with a spectral, ethereal quality.	4	t	2025-03-05 17:35:37.441912-05	["holographic","castle"]
314	/game-images/puns/crystal_rainforest.png	Imagine a lush rainforest where the foliage, wildlife, and even the rain are all made of glistening, multi-colored crystals.	5	t	2025-03-05 17:35:37.442747-05	["crystal","rainforest"]
315	/game-images/puns/invisible_symphony.png	Translate music into visual art. Picture soundwaves transforming into vibrant, invisible threads filling a concert hall with a palpable, mesmerizing energy.	6	t	2025-03-05 17:35:37.444221-05	["invisible","symphony"]
316	/game-images/puns/living_constellation.png	Dream of a constellation in the night sky, but the stars are living, glowing creatures, creating an awe-inspiring, organic celestial structure.	7	t	2025-03-05 17:35:37.445411-05	["living","constellation"]
317	/game-images/puns/recursive_jungle.png	Visualize a jungle where each element, from leaves to trees to animals, is a smaller jungle in itself, creating a visually complex, infinite loop of regression.	8	t	2025-03-05 17:35:37.446128-05	["recursive","jungle"]
318	/game-images/puns/quantum_symphony.png	Imagine a symphony orchestra where each musician exists in a superposition, creating infinite musical possibilities all playing simultaneously and somehow, harmoniously.	9	t	2025-03-05 17:35:37.446716-05	["quantum","symphony"]
319	/game-images/puns/four_dimensional_labyrinth.png	Picture a labyrinth that not only extends spatially, but also temporally. One can traverse not just left, right, forward, or back, but also forward and backward in time.	10	t	2025-03-05 17:35:37.447286-05	["four-dimensional","labyrinth"]
\.


--
-- Name: generative-art_game_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."generative-art_game_image_id_seq"', 319, true);


--
-- Name: generative-art_game_image generative-art_game_image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."generative-art_game_image"
    ADD CONSTRAINT "generative-art_game_image_pkey" PRIMARY KEY (id);


--
-- Name: game_image_path_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX game_image_path_idx ON public."generative-art_game_image" USING btree (image_path);


--
-- PostgreSQL database dump complete
--

