CREATE TABLE IF NOT EXISTS "generative-art_game_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"image_path" varchar(512) NOT NULL,
	"original_prompt" text NOT NULL,
	"difficulty" integer DEFAULT 1,
	"active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_game_leaderboard" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_leaderboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"game_image_id" integer NOT NULL,
	"best_score" real NOT NULL,
	"prompt_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_game_prompt" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_prompt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_image_id" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"prompt_text" text NOT NULL,
	"generated_image_path" varchar(512),
	"similarity_score" real,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_game_image_id_generative-art_game_image_id_fk" FOREIGN KEY ("game_image_id") REFERENCES "public"."generative-art_game_image"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_prompt_id_generative-art_game_prompt_id_fk" FOREIGN KEY ("prompt_id") REFERENCES "public"."generative-art_game_prompt"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_prompt" ADD CONSTRAINT "generative-art_game_prompt_game_image_id_generative-art_game_image_id_fk" FOREIGN KEY ("game_image_id") REFERENCES "public"."generative-art_game_image"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_prompt" ADD CONSTRAINT "generative-art_game_prompt_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_image_path_idx" ON "generative-art_game_image" USING btree ("image_path");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_leaderboard_user_id_idx" ON "generative-art_game_leaderboard" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_leaderboard_image_id_idx" ON "generative-art_game_leaderboard" USING btree ("game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unique_user_per_image_idx" ON "generative-art_game_leaderboard" USING btree ("user_id","game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_prompt_image_id_idx" ON "generative-art_game_prompt" USING btree ("game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_prompt_user_id_idx" ON "generative-art_game_prompt" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unique_prompt_per_image_idx" ON "generative-art_game_prompt" USING btree ("game_image_id","prompt_text");