CREATE TABLE IF NOT EXISTS "generative-art_art_piece" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_art_piece_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"config" json NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_game_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"image_path" varchar(512) NOT NULL,
	"original_prompt" text NOT NULL,
	"target_words" json NOT NULL,
	"difficulty" integer DEFAULT 1 NOT NULL,
	"active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_game_leaderboard" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_leaderboard_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256) NOT NULL,
	"game_image_id" integer NOT NULL,
	"best_score" real NOT NULL,
	"prompt_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_game_prompt" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generative-art_game_prompt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_image_id" integer NOT NULL,
	"user_id" varchar(256) NOT NULL,
	"prompt_text" text NOT NULL,
	"generated_image_path" varchar(512),
	"similarity_score" real,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_like" (
	"user_id" varchar(256) NOT NULL,
	"art_piece_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "generative-art_like_user_id_art_piece_id_pk" PRIMARY KEY("user_id","art_piece_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "generative-art_user" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"username" varchar(256) NOT NULL,
	"first_name" varchar(256),
	"last_name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "generative-art_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_art_piece" ADD CONSTRAINT "generative-art_art_piece_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_game_image_id_generative-art_game_image_id_fk" FOREIGN KEY ("game_image_id") REFERENCES "public"."generative-art_game_image"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_leaderboard" ADD CONSTRAINT "generative-art_game_leaderboard_prompt_id_generative-art_game_prompt_id_fk" FOREIGN KEY ("prompt_id") REFERENCES "public"."generative-art_game_prompt"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_prompt" ADD CONSTRAINT "generative-art_game_prompt_game_image_id_generative-art_game_image_id_fk" FOREIGN KEY ("game_image_id") REFERENCES "public"."generative-art_game_image"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_game_prompt" ADD CONSTRAINT "generative-art_game_prompt_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_like" ADD CONSTRAINT "generative-art_like_user_id_generative-art_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."generative-art_user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "generative-art_like" ADD CONSTRAINT "generative-art_like_art_piece_id_generative-art_art_piece_id_fk" FOREIGN KEY ("art_piece_id") REFERENCES "public"."generative-art_art_piece"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "art_piece_user_id_idx" ON "generative-art_art_piece" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_image_path_idx" ON "generative-art_game_image" USING btree ("image_path");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_leaderboard_user_id_idx" ON "generative-art_game_leaderboard" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_leaderboard_image_id_idx" ON "generative-art_game_leaderboard" USING btree ("game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unique_user_per_image_idx" ON "generative-art_game_leaderboard" USING btree ("user_id","game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_prompt_image_id_idx" ON "generative-art_game_prompt" USING btree ("game_image_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "game_prompt_user_id_idx" ON "generative-art_game_prompt" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unique_prompt_per_image_idx" ON "generative-art_game_prompt" USING btree ("game_image_id","prompt_text");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "like_art_piece_id_idx" ON "generative-art_like" USING btree ("art_piece_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "username_idx" ON "generative-art_user" USING btree ("username");